bind 127.0.0.1
port 6379
daemonize no
supervised systemd
dir /var/lib/redis
logfile /var/log/redis/redis-server.log
pidfile /run/redis/redis-server.pid
appendonly yes
appendfsync everysec
maxmemory 256mb
maxmemory-policy allkeys-lru
